2020-02-16 21:37:22,739 (1361/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-05-10 20:56:51,384 (2529260/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-05-10 20:58:23,607 (2529260/MainThread) pgcli.pgexecute ERROR - sql: 'clear', error: SyntaxError('syntax error at or near "clear"\nLINE 1: clear\n        ^\n')
2020-05-10 20:58:23,607 (2529260/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "clear"\nLINE 1: clear\n        ^\n\n'
2020-05-10 20:58:35,621 (2530079/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-05-10 21:03:59,462 (2532611/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-05-10 21:13:07,352 (2532611/MainThread) pgcli.pgexecute ERROR - sql: 'clear', error: SyntaxError('syntax error at or near "clear"\nLINE 1: clear\n        ^\n')
2020-05-10 21:13:07,353 (2532611/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "clear"\nLINE 1: clear\n        ^\n\n'
2020-05-10 21:13:20,677 (2532611/MainThread) pgcli.pgexecute ERROR - sql: 'select * from v_statements', error: DivisionByZero('division by zero\n')
2020-05-10 21:13:20,677 (2532611/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.DivisionByZero: division by zero\n\n'
2020-05-10 21:22:04,918 (2541095/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-05-10 21:22:04,979 (2541095/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/main.py", line 566, in connect\n    raise e\n  File "/usr/lib/python3.8/site-packages/pgcli/main.py", line 553, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 215, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 255, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/lib/python3.8/site-packages/psycopg2/__init__.py", line 126, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/run/postgresql/.s.PGSQL.5432"?\n\n'
2020-05-10 21:22:47,868 (2541423/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-05-10 21:26:27,804 (2541423/MainThread) pgcli.pgexecute ERROR - sql: 'clear', error: SyntaxError('syntax error at or near "clear"\nLINE 1: clear\n        ^\n')
2020-05-10 21:26:27,805 (2541423/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "clear"\nLINE 1: clear\n        ^\n\n'
2020-05-10 21:37:16,770 (2548204/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-05-10 21:39:14,186 (2548204/MainThread) pgcli.pgexecute ERROR - sql: 'select * from v_statements where year > 2018 and cash_to_debt not null order by cash_to_debt desc', error: SyntaxError('syntax error at or near "not"\nLINE 1: ...m v_statements where year > 2018 and cash_to_debt not null o...\n                                                             ^\n')
2020-05-10 21:39:14,187 (2548204/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "not"\nLINE 1: ...m v_statements where year > 2018 and cash_to_debt not null o...\n                                                             ^\n\n'
2020-05-10 21:45:36,723 (2548204/MainThread) pgcli.pgexecute ERROR - sql: 'select * from v_statements where instrument_id = 813 year > 2018 and not cash_to_debt is null order by cash_to_debt desc', error: SyntaxError('syntax error at or near "year"\nLINE 1: ...ect * from v_statements where instrument_id = 813 year > 201...\n                                                             ^\n')
2020-05-10 21:45:36,724 (2548204/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "year"\nLINE 1: ...ect * from v_statements where instrument_id = 813 year > 201...\n                                                             ^\n\n'
2020-05-10 22:11:51,263 (2548204/MainThread) pgcli.pgexecute ERROR - sql: 'select * from v_statements where year > 2018 and not cash_to_debt is null and not operating_roa is null not net_income_to_rev is null and net_income_to_rev > 0.1 order by operating_roa desc', error: SyntaxError('syntax error at or near "not"\nLINE 1: ...ash_to_debt is null and not operating_roa is null not net_in...\n                                                             ^\n')
2020-05-10 22:11:51,263 (2548204/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "not"\nLINE 1: ...ash_to_debt is null and not operating_roa is null not net_in...\n                                                             ^\n\n'
2020-05-10 22:29:58,003 (2548204/MainThread) pgcli.pgexecute ERROR - sql: 'clear', error: SyntaxError('syntax error at or near "clear"\nLINE 1: clear\n        ^\n')
2020-05-10 22:29:58,003 (2548204/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "clear"\nLINE 1: clear\n        ^\n\n'
2020-05-10 23:07:48,058 (2548204/MainThread) pgcli.pgexecute ERROR - sql: 'create or replace view v_best_statements as\n  select\n    name,\n\tsymbol,\n\tpe_calc,\n\tdiv_yeild,\n\top_income_to_rev,\n\tnet_income_to_rev,\n\top_cash_to_rev,\n\toperating_roa,\n\tcash_to_debt\n  from v_statements\n  where year >= 2019\n  and not cash_to_debt is null\n  and not operating_roa is null\n  and not op_cash_to_rev is null\n  and not net_income_to_rev is null\n  and net_income_to_rev > 0.1\n  and not op_income_to_rev is null\n  order by operating_roa desc', error: UndefinedColumn('column "div_yeild" does not exist\nLINE 6:  div_yeild,\n         ^\nHINT:  Perhaps you meant to reference the column "v_statements.div_yield".\n')
2020-05-10 23:07:48,058 (2548204/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "div_yeild" does not exist\nLINE 6:  div_yeild,\n         ^\nHINT:  Perhaps you meant to reference the column "v_statements.div_yield".\n\n'
2020-05-10 23:07:48,058 (2548204/MainThread) pgcli.pgexecute ERROR - sql: '\\i views.plsql', error: UndefinedColumn('column "div_yeild" does not exist\nLINE 6:  div_yeild,\n         ^\nHINT:  Perhaps you meant to reference the column "v_statements.div_yield".\n')
2020-05-10 23:07:48,058 (2548204/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 402, in run\n    for result in pgspecial.execute(cur, sql):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "div_yeild" does not exist\nLINE 6:  div_yeild,\n         ^\nHINT:  Perhaps you meant to reference the column "v_statements.div_yield".\n\n'
2020-05-10 23:19:38,355 (2548204/MainThread) pgcli.pgexecute ERROR - sql: 'create or replace view v_best_statements as\n  select\n    s.name,\n\ts.symbol,\n\ts.pe_calc,\n\ts.div_yield,\n\tq.market_cap,\n\ts.op_income_to_rev,\n\ts.net_income_to_rev,\n\ts.op_cash_to_rev,\n\ts.operating_roa,\n\ts.cash_to_debt\n  from v_statements as s\n  inner join last_quote as q\n  on q.instrument_id = s.instrument_id\n  where year >= 2019\n  and not s.cash_to_debt is null\n  and not s.operating_roa is null\n  and not s.op_cash_to_rev is null\n  and not s.net_income_to_rev is null\n  and s.net_income_to_rev > 0.1\n  and not s.op_income_to_rev is null\n  order by s.operating_roa desc', error: UndefinedTable('relation "last_quote" does not exist\nLINE 14:   inner join last_quote as q\n                      ^\n')
2020-05-10 23:19:38,355 (2548204/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedTable: relation "last_quote" does not exist\nLINE 14:   inner join last_quote as q\n                      ^\n\n'
2020-05-10 23:19:38,355 (2548204/MainThread) pgcli.pgexecute ERROR - sql: '\\i views.plsql', error: UndefinedTable('relation "last_quote" does not exist\nLINE 14:   inner join last_quote as q\n                      ^\n')
2020-05-10 23:19:38,356 (2548204/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 402, in run\n    for result in pgspecial.execute(cur, sql):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedTable: relation "last_quote" does not exist\nLINE 14:   inner join last_quote as q\n                      ^\n\n'
2020-05-10 23:19:54,508 (2548204/MainThread) pgcli.pgexecute ERROR - sql: 'create or replace view v_best_statements as\n  select\n    s.name,\n\ts.symbol,\n\ts.pe_calc,\n\ts.div_yield,\n\tq.market_cap,\n\ts.op_income_to_rev,\n\ts.net_income_to_rev,\n\ts.op_cash_to_rev,\n\ts.operating_roa,\n\ts.cash_to_debt\n  from v_statements as s\n  inner join v_last_quote as q\n  on q.instrument_id = s.instrument_id\n  where year >= 2019\n  and not s.cash_to_debt is null\n  and not s.operating_roa is null\n  and not s.op_cash_to_rev is null\n  and not s.net_income_to_rev is null\n  and s.net_income_to_rev > 0.1\n  and not s.op_income_to_rev is null\n  order by s.operating_roa desc', error: InvalidTableDefinition('cannot change name of view column "op_income_to_rev" to "market_cap"\n')
2020-05-10 23:19:54,508 (2548204/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.InvalidTableDefinition: cannot change name of view column "op_income_to_rev" to "market_cap"\n\n'
2020-05-10 23:19:54,509 (2548204/MainThread) pgcli.pgexecute ERROR - sql: '\\i views.plsql', error: InvalidTableDefinition('cannot change name of view column "op_income_to_rev" to "market_cap"\n')
2020-05-10 23:19:54,509 (2548204/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 402, in run\n    for result in pgspecial.execute(cur, sql):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.InvalidTableDefinition: cannot change name of view column "op_income_to_rev" to "market_cap"\n\n'
2020-05-10 23:22:33,317 (2548204/MainThread) pgcli.pgexecute ERROR - sql: 'select * from v_best_statements limit 5', error: QueryCanceled('canceling statement due to user request\n')
2020-05-10 23:22:33,318 (2548204/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.QueryCanceled: canceling statement due to user request\n\n'
2020-05-10 23:28:25,119 (2548204/MainThread) pgcli.pgexecute ERROR - sql: 'drop view v_statements', error: DependentObjectsStillExist('cannot drop view v_statements because other objects depend on it\nDETAIL:  view v_best_statements depends on view v_statements\nHINT:  Use DROP ... CASCADE to drop the dependent objects too.\n')
2020-05-10 23:28:25,120 (2548204/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.DependentObjectsStillExist: cannot drop view v_statements because other objects depend on it\nDETAIL:  view v_best_statements depends on view v_statements\nHINT:  Use DROP ... CASCADE to drop the dependent objects too.\n\n'
2020-05-10 23:30:51,078 (2548204/MainThread) pgcli.pgexecute ERROR - sql: 'create or replace view v_best_statements as\n  select\n    s.name,\n\ts.symbol,\n\ts.market_cap / 1e9 as market_cap_B,\n\ts.pe_calc,\n\ts.div_yield,\n\ts.op_income_to_rev,\n\ts.net_income_to_rev,\n\ts.op_cash_to_rev,\n\ts.operating_roa,\n\ts.cash_to_debt\n  from v_statements as s\n  where year >= 2019\n  and not s.cash_to_debt is null\n  and not s.operating_roa is null\n  and not s.op_cash_to_rev is null\n  and not s.net_income_to_rev is null\n  and s.net_income_to_rev > 0.1\n  and not s.op_income_to_rev is null\n  order by s.operating_roa desc', error: InvalidTableDefinition('cannot change name of view column "market_cap" to "market_cap_b"\n')
2020-05-10 23:30:51,078 (2548204/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.InvalidTableDefinition: cannot change name of view column "market_cap" to "market_cap_b"\n\n'
2020-05-10 23:30:51,078 (2548204/MainThread) pgcli.pgexecute ERROR - sql: '\\i views.plsql', error: InvalidTableDefinition('cannot change name of view column "market_cap" to "market_cap_b"\n')
2020-05-10 23:30:51,078 (2548204/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 402, in run\n    for result in pgspecial.execute(cur, sql):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.InvalidTableDefinition: cannot change name of view column "market_cap" to "market_cap_b"\n\n'
2020-05-17 14:29:19,474 (502148/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-05-17 18:28:43,039 (502148/MainThread) pgcli.pgexecute ERROR - sql: 'insert into symbols (instrument_id, host_id, symbol, name) values', error: SyntaxError('syntax error at end of input\nLINE 1: ...t into symbols (instrument_id, host_id, symbol, name) values\n                                                                       ^\n')
2020-05-17 18:28:43,039 (502148/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at end of input\nLINE 1: ...t into symbols (instrument_id, host_id, symbol, name) values\n                                                                       ^\n\n'
2020-05-17 18:41:40,741 (502148/MainThread) pgcli.pgexecute ERROR - sql: 'clear', error: SyntaxError('syntax error at or near "clear"\nLINE 1: clear\n        ^\n')
2020-05-17 18:41:40,741 (502148/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "clear"\nLINE 1: clear\n        ^\n\n'
2020-05-17 20:07:31,046 (502148/MainThread) pgcli.pgexecute ERROR - sql: 'clear', error: SyntaxError('syntax error at or near "clear"\nLINE 1: clear\n        ^\n')
2020-05-17 20:07:31,046 (502148/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "clear"\nLINE 1: clear\n        ^\n\n'
2020-05-17 21:30:39,455 (698750/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-05-17 21:33:42,577 (700213/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-05-17 22:30:41,272 (700213/MainThread) pgcli.pgexecute ERROR - sql: 'drop view v_instrument_pnl', error: DependentObjectsStillExist('cannot drop view v_instrument_pnl because other objects depend on it\nDETAIL:  view v_trading_pnl depends on view v_instrument_pnl\nview v_account_balances depends on view v_trading_pnl\nHINT:  Use DROP ... CASCADE to drop the dependent objects too.\n')
2020-05-17 22:30:41,273 (700213/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.DependentObjectsStillExist: cannot drop view v_instrument_pnl because other objects depend on it\nDETAIL:  view v_trading_pnl depends on view v_instrument_pnl\nview v_account_balances depends on view v_trading_pnl\nHINT:  Use DROP ... CASCADE to drop the dependent objects too.\n\n'
2020-05-17 22:36:34,234 (729690/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-05-17 22:38:17,656 (729690/MainThread) pgcli.pgexecute ERROR - sql: '--profit and loss by instrument \ncreate or replace view v_instrument_pnl as\n  select \n    nq.instrument_id,\n    nq.account_id,\n    nq.trade_start_id,\n    nq.quantity_out,\n    lq.time_of,\n    o.price as price_basis,\n\tsign(o.order_type_id) * o.quantity * o.leverage * o.price as cost_basis,\n    lq.quote,\n    nq.pnl - o.price * nq.quantity_out as pnl_realized,\n    nq.pnl - lq.quote * nq.quantity_out as pnl,\n\tpnl / cost_basis as pct_pnl\n  from v_instrument_pnl_noquote as nq\n  inner join v_last_quote as lq\n    on nq.instrument_id = lq.instrument_id\n  inner join v_orders as o\n    on nq.trade_start_id = o.id', error: UndefinedColumn('column "cost_basis" does not exist\nLINE 14:  pnl / cost_basis as pct_pnl\n                ^\n')
2020-05-17 22:38:17,656 (729690/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "cost_basis" does not exist\nLINE 14:  pnl / cost_basis as pct_pnl\n                ^\n\n'
2020-05-17 22:38:17,657 (729690/MainThread) pgcli.pgexecute ERROR - sql: '\\i views.plsql', error: UndefinedColumn('column "cost_basis" does not exist\nLINE 14:  pnl / cost_basis as pct_pnl\n                ^\n')
2020-05-17 22:38:17,657 (729690/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 402, in run\n    for result in pgspecial.execute(cur, sql):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "cost_basis" does not exist\nLINE 14:  pnl / cost_basis as pct_pnl\n                ^\n\n'
2020-05-24 14:35:03,673 (141610/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-05-28 10:22:31,394 (1288351/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-06-08 20:02:27,250 (114964/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-07-29 20:22:00,469 (3363325/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-08-30 11:06:30,554 (1694797/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-09-13 21:46:49,966 (2664285/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-09-29 21:02:23,045 (106352/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-09-29 21:05:01,060 (106352/MainThread) pgcli.pgexecute ERROR - sql: 'select * from v_best_statements where instrument_id < 500', error: UndefinedColumn('column "instrument_id" does not exist\nLINE 1: select * from v_best_statements where instrument_id < 500\n                                              ^\n')
2020-09-29 21:05:01,060 (106352/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "instrument_id" does not exist\nLINE 1: select * from v_best_statements where instrument_id < 500\n                                              ^\n\n'
2020-09-29 21:22:29,403 (116082/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-09-29 21:23:43,780 (116082/MainThread) pgcli.pgexecute ERROR - sql: 'select count(instrument_id) from v_pulls_due inner join v_symbols on v_symbols.instrument_id = v_pulls_due.instrument_id', error: AmbiguousColumn('column reference "instrument_id" is ambiguous\nLINE 1: select count(instrument_id) from v_pulls_due inner join v_sy...\n                     ^\n')
2020-09-29 21:23:43,781 (116082/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.AmbiguousColumn: column reference "instrument_id" is ambiguous\nLINE 1: select count(instrument_id) from v_pulls_due inner join v_sy...\n                     ^\n\n'
2020-09-29 21:28:10,713 (116082/MainThread) pgcli.pgexecute ERROR - sql: 'select unique count(instrument_id) from v_symbols where host_id=4', error: SyntaxError('syntax error at or near "count"\nLINE 1: select unique count(instrument_id) from v_symbols where host...\n                      ^\n')
2020-09-29 21:28:10,713 (116082/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "count"\nLINE 1: select unique count(instrument_id) from v_symbols where host...\n                      ^\n\n'
2020-09-29 21:28:23,586 (116082/MainThread) pgcli.pgexecute ERROR - sql: 'select count(unique instrument_id) from v_symbols where host_id=4', error: SyntaxError('syntax error at or near "instrument_id"\nLINE 1: select count(unique instrument_id) from v_symbols where host...\n                            ^\n')
2020-09-29 21:28:23,586 (116082/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "instrument_id"\nLINE 1: select count(unique instrument_id) from v_symbols where host...\n                            ^\n\n'
2020-09-29 21:28:35,332 (116082/MainThread) pgcli.pgexecute ERROR - sql: 'select unique instrument_id from v_symbols where host_id=4', error: SyntaxError('syntax error at or near "instrument_id"\nLINE 1: select unique instrument_id from v_symbols where host_id=4\n                      ^\n')
2020-09-29 21:28:35,332 (116082/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "instrument_id"\nLINE 1: select unique instrument_id from v_symbols where host_id=4\n                      ^\n\n'
2020-09-29 21:43:06,203 (125801/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-09-29 21:43:13,550 (125801/MainThread) pgcli.pgexecute ERROR - sql: 'inner join instruments as ins\n\t  on ins.instrument_id = ii.instrument_id\n  where ins.active\n\n--all the data pulls that are due, based on the indexes and last pulls\ncreate or replace view v_pulls_due as\n  select *\n  from v_data_pulls\n  where time_since is null or time_since > period or not successful\n  order by index_id, instrument_id', error: SyntaxError('syntax error at or near "inner"\nLINE 1: inner join instruments as ins\n        ^\n')
2020-09-29 21:43:13,550 (125801/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "inner"\nLINE 1: inner join instruments as ins\n        ^\n\n'
2020-09-29 21:43:13,550 (125801/MainThread) pgcli.pgexecute ERROR - sql: '\\i views.plsql', error: SyntaxError('syntax error at or near "inner"\nLINE 1: inner join instruments as ins\n        ^\n')
2020-09-29 21:43:13,550 (125801/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 398, in run\n    for result in pgspecial.execute(cur, sql):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "inner"\nLINE 1: inner join instruments as ins\n        ^\n\n'
2020-09-29 21:43:45,404 (125801/MainThread) pgcli.pgexecute ERROR - sql: '--all the data pulls for each instrument-index\ncreate or replace view v_data_pulls as\n  select\n    ii.index_id,\n    ii.instrument_id,\n    lp.successful,\n    now() - lp.time_of as time_since,\n    i.period,\n    i.name as index_name\n  from v_last_pulls as lp\n  full outer join instrument_indexes as ii\n    on ii.index_id = lp.index_id and ii.instrument_id = lp.instrument_id\n    inner join indexes as i\n      on i.id = ii.index_id\n\tinner join instruments as ins\n\t  on ins.instrument_id = ii.instrument_id\n  where ins.active', error: UndefinedColumn('column ins.instrument_id does not exist\nLINE 16:    on ins.instrument_id = ii.instrument_id\n               ^\nHINT:  Perhaps you meant to reference the column "ii.instrument_id".\n')
2020-09-29 21:43:45,404 (125801/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column ins.instrument_id does not exist\nLINE 16:    on ins.instrument_id = ii.instrument_id\n               ^\nHINT:  Perhaps you meant to reference the column "ii.instrument_id".\n\n'
2020-09-29 21:43:45,404 (125801/MainThread) pgcli.pgexecute ERROR - sql: '\\i views.plsql', error: UndefinedColumn('column ins.instrument_id does not exist\nLINE 16:    on ins.instrument_id = ii.instrument_id\n               ^\nHINT:  Perhaps you meant to reference the column "ii.instrument_id".\n')
2020-09-29 21:43:45,404 (125801/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 398, in run\n    for result in pgspecial.execute(cur, sql):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column ins.instrument_id does not exist\nLINE 16:    on ins.instrument_id = ii.instrument_id\n               ^\nHINT:  Perhaps you meant to reference the column "ii.instrument_id".\n\n'
2020-09-29 21:51:49,808 (125801/MainThread) pgcli.pgexecute ERROR - sql: 'select v_pulls_due.instrument_id v_symbols.instrument_id from v_pulls_due left join v_symbols on v_symbols.instrument_id = v_pulls_due.instrument_id where v_symbols.host_id=4', error: SyntaxError('syntax error at or near "."\nLINE 1: select v_pulls_due.instrument_id v_symbols.instrument_id fro...\n                                                  ^\n')
2020-09-29 21:51:49,809 (125801/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "."\nLINE 1: select v_pulls_due.instrument_id v_symbols.instrument_id fro...\n                                                  ^\n\n'
2020-09-29 21:53:39,473 (125801/MainThread) pgcli.pgexecute ERROR - sql: 'select count(v_pulls_due.instrument_id, v_symbols.instrument_id) from v_pulls_due left join v_symbols on v_symbols.instrument_id = v_pulls_due.instrument_id where v_symbols.host_id=4', error: UndefinedFunction('function count(integer, integer) does not exist\nLINE 1: select count(v_pulls_due.instrument_id, v_symbols.instrument...\n               ^\nHINT:  No function matches the given name and argument types. You might need to add explicit type casts.\n')
2020-09-29 21:53:39,473 (125801/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedFunction: function count(integer, integer) does not exist\nLINE 1: select count(v_pulls_due.instrument_id, v_symbols.instrument...\n               ^\nHINT:  No function matches the given name and argument types. You might need to add explicit type casts.\n\n'
2020-09-29 21:54:03,806 (125801/MainThread) pgcli.pgexecute ERROR - sql: 'select count(v_pulls_due.instrument_id), v_symbols.instrument_id from v_pulls_due left join v_symbols on v_symbols.instrument_id = v_pulls_due.instrument_id where v_symbols.host_id=4', error: GroupingError('column "v_symbols.instrument_id" must appear in the GROUP BY clause or be used in an aggregate function\nLINE 1: select count(v_pulls_due.instrument_id), v_symbols.instrumen...\n                                                 ^\n')
2020-09-29 21:54:03,807 (125801/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.GroupingError: column "v_symbols.instrument_id" must appear in the GROUP BY clause or be used in an aggregate function\nLINE 1: select count(v_pulls_due.instrument_id), v_symbols.instrumen...\n                                                 ^\n\n'
2020-09-29 22:02:12,689 (125801/MainThread) pgcli.pgexecute ERROR - sql: 'select distinct p.instrument_id s.instrument_id from v_pulls_due as p left join v_symbols as s on s.instrument_id = p.instrument_id where host_id=4', error: SyntaxError('syntax error at or near "."\nLINE 1: select distinct p.instrument_id s.instrument_id from v_pulls...\n                                         ^\n')
2020-09-29 22:02:12,690 (125801/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "."\nLINE 1: select distinct p.instrument_id s.instrument_id from v_pulls...\n                                         ^\n\n'
2020-09-29 22:07:04,287 (125801/MainThread) pgcli.pgexecute ERROR - sql: 'select distinct p.instrument_id from v_pulls_due as p full left join v_symbols as s on s.instrument_id = p.instrument_id and s.host_id=4', error: SyntaxError('syntax error at or near "left"\nLINE 1: ...stinct p.instrument_id from v_pulls_due as p full left join ...\n                                                             ^\n')
2020-09-29 22:07:04,288 (125801/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "left"\nLINE 1: ...stinct p.instrument_id from v_pulls_due as p full left join ...\n                                                             ^\n\n'
2020-09-29 22:10:58,081 (125801/MainThread) pgcli.pgexecute ERROR - sql: 'select * from instruments where (instrument_id > 1655 and instrument_id < 1666)', error: UndefinedColumn('column "instrument_id" does not exist\nLINE 1: select * from instruments where (instrument_id > 1655 and in...\n                                         ^\n')
2020-09-29 22:10:58,081 (125801/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "instrument_id" does not exist\nLINE 1: select * from instruments where (instrument_id > 1655 and in...\n                                         ^\n\n'
2020-09-29 22:12:18,496 (125801/MainThread) pgcli.pgexecute ERROR - sql: 'select * from symbols where and (instrument_id > 1655 and instrument_id < 1666)', error: SyntaxError('syntax error at or near "and"\nLINE 1: select * from symbols where and (instrument_id > 1655 and in...\n                                    ^\n')
2020-09-29 22:12:18,496 (125801/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "and"\nLINE 1: select * from symbols where and (instrument_id > 1655 and in...\n                                    ^\n\n'
2020-10-01 23:38:35,361 (942247/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-04 21:49:18,692 (1850872/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-04 21:50:42,995 (1850872/MainThread) pgcli.pgexecute ERROR - sql: 'select * from v_largest_companies limit 500', error: QueryCanceled('canceling statement due to user request\n')
2020-10-04 21:50:42,996 (1850872/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.QueryCanceled: canceling statement due to user request\n\n'
2020-10-04 21:53:12,268 (1850872/MainThread) pgcli.pgexecute ERROR - sql: 'select * from v_largest_companies where market_cap_b is not null limit 500', error: QueryCanceled('canceling statement due to user request\n')
2020-10-04 21:53:12,269 (1850872/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.QueryCanceled: canceling statement due to user request\n\n'
2020-10-04 21:53:51,545 (1850872/MainThread) pgcli.pgexecute ERROR - sql: 'select top 500 * from v_largest_companies where market_cap_b is not null', error: SyntaxError('syntax error at or near "500"\nLINE 1: select top 500 * from v_largest_companies where market_cap_b...\n                   ^\n')
2020-10-04 21:53:51,545 (1850872/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "500"\nLINE 1: select top 500 * from v_largest_companies where market_cap_b...\n                   ^\n\n'
2020-10-04 21:57:06,121 (1850872/MainThread) pgcli.pgexecute ERROR - sql: 'select * from v_largest_companies where market_cap_b is not null fetch first 500 rows only', error: QueryCanceled('canceling statement due to user request\n')
2020-10-04 21:57:06,121 (1850872/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.QueryCanceled: canceling statement due to user request\n\n'
2020-10-04 21:57:14,537 (1850872/MainThread) pgcli.pgexecute ERROR - sql: 'select * from v_largest_companies where market_cap_b is not null fetch first 5rows only', error: QueryCanceled('canceling statement due to user request\n')
2020-10-04 21:57:14,537 (1850872/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.QueryCanceled: canceling statement due to user request\n\n'
2020-10-04 21:57:48,576 (1850872/MainThread) pgcli.pgexecute ERROR - sql: 'select * from v_largest_companies where market_cap_b is not null limit 5', error: QueryCanceled('canceling statement due to user request\n')
2020-10-04 21:57:48,576 (1850872/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.QueryCanceled: canceling statement due to user request\n\n'
2020-10-04 22:00:34,082 (1850872/MainThread) pgcli.pgexecute ERROR - sql: '--largest by market cap\ncreate or replace view v_largest_companies as\n  with unordered as (\n  select\n    q.instrument_id,\n    s.name,\n    s.symbol,\n    q.market_cap / 1e9 as market_cap_b\n  from v_last_quote as q\n  inner join v_symbols as s\n  on q.instrument_id = s.instrument_id and s.host_id = 4 \n  where q.market_cap is not null )\n  select\n    row_number() over (order by market_cap_b desc),\n    * \n  from unordered \n  where row_number <= 500', error: UndefinedColumn('column "row_number" does not exist\nLINE 17:   where row_number <= 500\n                 ^\n')
2020-10-04 22:00:34,083 (1850872/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "row_number" does not exist\nLINE 17:   where row_number <= 500\n                 ^\n\n'
2020-10-04 22:00:34,083 (1850872/MainThread) pgcli.pgexecute ERROR - sql: '\\i views.plsql', error: UndefinedColumn('column "row_number" does not exist\nLINE 17:   where row_number <= 500\n                 ^\n')
2020-10-04 22:00:34,083 (1850872/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 398, in run\n    for result in pgspecial.execute(cur, sql):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "row_number" does not exist\nLINE 17:   where row_number <= 500\n                 ^\n\n'
2020-10-04 22:01:14,469 (1850872/MainThread) pgcli.pgexecute ERROR - sql: '--largest by market cap\ncreate or replace view v_largest_companies as\n  with unordered as (\n  select\n    q.instrument_id,\n    s.name,\n    s.symbol,\n    q.market_cap / 1e9 as market_cap_b\n  from v_last_quote as q\n  inner join v_symbols as s\n  on q.instrument_id = s.instrument_id and s.host_id = 4 \n  where q.market_cap is not null )\n  select\n    row_number() over (order by market_cap_b desc) as rank,\n    * \n  from unordered \n  where rank <= 500', error: UndefinedColumn('column "rank" does not exist\nLINE 17:   where rank <= 500\n                 ^\n')
2020-10-04 22:01:14,470 (1850872/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "rank" does not exist\nLINE 17:   where rank <= 500\n                 ^\n\n'
2020-10-04 22:01:14,470 (1850872/MainThread) pgcli.pgexecute ERROR - sql: '\\i views.plsql', error: UndefinedColumn('column "rank" does not exist\nLINE 17:   where rank <= 500\n                 ^\n')
2020-10-04 22:01:14,470 (1850872/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 398, in run\n    for result in pgspecial.execute(cur, sql):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "rank" does not exist\nLINE 17:   where rank <= 500\n                 ^\n\n'
2020-10-04 22:02:51,002 (1850872/MainThread) pgcli.pgexecute ERROR - sql: '--largest by market cap\ncreate or replace view v_largest_companies as\n  with unordered as (\n  select\n    q.instrument_id,\n    s.name,\n    s.symbol,\n    q.market_cap / 1e9 as market_cap_b\n  from v_last_quote as q\n  inner join v_symbols as s\n  on q.instrument_id = s.instrument_id and s.host_id = 4 \n  where q.market_cap is not null )\n  select\n    row_number() over (order by market_cap_b desc) as rank,\n    * \n  from unordered \n  limit 500', error: InvalidTableDefinition('cannot change name of view column "row_number" to "rank"\n')
2020-10-04 22:02:51,003 (1850872/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.InvalidTableDefinition: cannot change name of view column "row_number" to "rank"\n\n'
2020-10-04 22:02:51,003 (1850872/MainThread) pgcli.pgexecute ERROR - sql: '\\i views.plsql', error: InvalidTableDefinition('cannot change name of view column "row_number" to "rank"\n')
2020-10-04 22:02:51,003 (1850872/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 398, in run\n    for result in pgspecial.execute(cur, sql):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.InvalidTableDefinition: cannot change name of view column "row_number" to "rank"\n\n'
2020-10-04 22:03:23,325 (1850872/MainThread) pgcli.pgexecute ERROR - sql: 'select * from v_largest_companies', error: QueryCanceled('canceling statement due to user request\n')
2020-10-04 22:03:23,325 (1850872/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.QueryCanceled: canceling statement due to user request\n\n'
2020-10-04 22:07:52,438 (1850872/MainThread) pgcli.pgexecute ERROR - sql: 'select * from v_largest_companies2 order by market_cap_b desc limit 500', error: QueryCanceled('canceling statement due to user request\n')
2020-10-04 22:07:52,438 (1850872/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.QueryCanceled: canceling statement due to user request\n\n'
2020-10-04 22:19:12,428 (1850872/MainThread) pgcli.pgexecute ERROR - sql: '--largest by market cap\ncreate or replace view v_largest_companies as\n  with unordered as (\n  select\n    q.instrument_id,\n    s.name,\n    s.symbol,\n    q.market_cap / 1e9 as market_cap_b,\n    q.market_cap / sum(q.market_cap) * 100 as market_frac\n  from v_last_quote as q\n  inner join v_symbols as s\n  on q.instrument_id = s.instrument_id and s.host_id = 4 \n  where q.market_cap is not null and q.market_cap > 10e9)\n  select\n    row_number() over (order by market_cap_b desc),\n    * \n  from unordered', error: GroupingError('column "q.instrument_id" must appear in the GROUP BY clause or be used in an aggregate function\nLINE 5:     q.instrument_id,\n            ^\n')
2020-10-04 22:19:12,428 (1850872/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.GroupingError: column "q.instrument_id" must appear in the GROUP BY clause or be used in an aggregate function\nLINE 5:     q.instrument_id,\n            ^\n\n'
2020-10-04 22:19:12,428 (1850872/MainThread) pgcli.pgexecute ERROR - sql: '\\i views.plsql', error: GroupingError('column "q.instrument_id" must appear in the GROUP BY clause or be used in an aggregate function\nLINE 5:     q.instrument_id,\n            ^\n')
2020-10-04 22:19:12,429 (1850872/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 398, in run\n    for result in pgspecial.execute(cur, sql):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.GroupingError: column "q.instrument_id" must appear in the GROUP BY clause or be used in an aggregate function\nLINE 5:     q.instrument_id,\n            ^\n\n'
2020-10-04 22:40:21,954 (1850872/MainThread) pgcli.pgexecute ERROR - sql: 'pwd\n', error: SyntaxError('syntax error at or near "pwd"\nLINE 1: pwd\n        ^\n')
2020-10-04 22:40:21,955 (1850872/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "pwd"\nLINE 1: pwd\n        ^\n\n'
2020-10-04 22:40:44,311 (1874636/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-04 22:46:47,101 (1874636/MainThread) pgcli.pgexecute ERROR - sql: 'create or replace view v_best_statements as\n  select\n    s.name,\n\ts.symbol,\n\ts.year,\n\ts.market_cap / 1e9 as market_cap_B,\n\ts.pe_calc,\n\ts.div_yield,\n\ts.op_income_to_rev,\n\ts.net_income_to_rev,\n\ts.op_cash_to_rev,\n\ts.operating_roa,\n\ts.cash_to_debt\n  from v_statements as s\n  where year >= 2019\n  and not s.cash_to_debt is null\n  and not s.operating_roa is null\n  and not s.op_cash_to_rev is null\n  and not s.net_income_to_rev is null\n  and s.net_income_to_rev > 0.1\n  and not s.op_income_to_rev is null\n  order by s.operating_roa desc', error: InvalidTableDefinition('cannot change name of view column "market_cap_b" to "year"\n')
2020-10-04 22:46:47,102 (1874636/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.InvalidTableDefinition: cannot change name of view column "market_cap_b" to "year"\n\n'
2020-10-04 22:46:47,102 (1874636/MainThread) pgcli.pgexecute ERROR - sql: '\\i views.plsql', error: InvalidTableDefinition('cannot change name of view column "market_cap_b" to "year"\n')
2020-10-04 22:46:47,102 (1874636/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 398, in run\n    for result in pgspecial.execute(cur, sql):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.InvalidTableDefinition: cannot change name of view column "market_cap_b" to "year"\n\n'
2020-10-04 22:46:57,840 (1874636/MainThread) pgcli.pgexecute ERROR - sql: 'drop view v_best_statements', error: DependentObjectsStillExist('cannot drop view v_best_statements because other objects depend on it\nDETAIL:  view v_largest_best depends on view v_best_statements\nHINT:  Use DROP ... CASCADE to drop the dependent objects too.\n')
2020-10-04 22:46:57,841 (1874636/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.DependentObjectsStillExist: cannot drop view v_best_statements because other objects depend on it\nDETAIL:  view v_largest_best depends on view v_best_statements\nHINT:  Use DROP ... CASCADE to drop the dependent objects too.\n\n'
2020-10-04 23:00:16,640 (1874636/MainThread) pgcli.pgexecute ERROR - sql: 'create or replace view v_best_statements as\n  with best_statement as (\n  select\n    s.name,\n\ts.symbol,\n\ts.year,\n\ts.market_cap / 1e9 as market_cap_B,\n\ts.pe_calc,\n\ts.div_yield,\n\ts.op_income_to_rev,\n\ts.net_income_to_rev,\n\ts.op_cash_to_rev,\n\ts.operating_roa,\n\ts.cash_to_debt,\n\trow_number() over (partition by s.symbol order by s.year desc) as rk\n  from v_statements as s\n  where not s.cash_to_debt is null\n  and not s.operating_roa is null\n  and not s.op_cash_to_rev is null\n  and not s.net_income_to_rev is null\n  and s.net_income_to_rev > 0.1\n  and not s.op_income_to_rev is null )\n  select\n    *\n  from best_statement\n  where rk=1\n  order by s.market_cap_B desc', error: UndefinedTable('missing FROM-clause entry for table "s"\nLINE 27:   order by s.market_cap_B desc\n                    ^\n')
2020-10-04 23:00:16,640 (1874636/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedTable: missing FROM-clause entry for table "s"\nLINE 27:   order by s.market_cap_B desc\n                    ^\n\n'
2020-10-04 23:00:16,640 (1874636/MainThread) pgcli.pgexecute ERROR - sql: '\\i views.plsql', error: UndefinedTable('missing FROM-clause entry for table "s"\nLINE 27:   order by s.market_cap_B desc\n                    ^\n')
2020-10-04 23:00:16,640 (1874636/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 398, in run\n    for result in pgspecial.execute(cur, sql):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedTable: missing FROM-clause entry for table "s"\nLINE 27:   order by s.market_cap_B desc\n                    ^\n\n'
2020-10-05 11:48:19,144 (2005308/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-05 11:49:02,699 (2005308/MainThread) pgcli.pgexecute ERROR - sql: 'clear\n', error: SyntaxError('syntax error at or near "clear"\nLINE 1: clear\n        ^\n')
2020-10-05 11:49:02,700 (2005308/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "clear"\nLINE 1: clear\n        ^\n\n'
2020-10-05 11:51:46,665 (2006954/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-05 11:51:52,815 (2006954/MainThread) pgcli.pgexecute ERROR - sql: "create or replace view v_best_statements as\n  with best_statement as (\n  select\n    s.name,\n\ts.symbol,\n\ts.year,\n\ts.market_cap / 1e9 as market_cap_B,\n\ts.pe_calc,\n\ts.div_yield,\n\ts.op_income_to_rev,\n\ts.net_income_to_rev,\n\ts.op_cash_to_rev,\n\ts.operating_roa,\n\ts.cash_to_debt,\n\trow_number() over (partition by s.symbol order by s.year desc) as rk\n  from v_statements as s\n  where s.year >= 2019\n  'and s.pe_calc > 0 and s.pe_calc < 40\n  and not s.cash_to_debt is null\n  and not s.operating_roa is null\n  and not s.op_cash_to_rev is null\n  and not s.net_income_to_rev is null\n  and not s.op_income_to_rev is null\n  and s.market_cap / 1e9 > 10)\n  select\n    *\n  from best_statement as b\n  where b.rk=1\n  order by b.market_cap_B desc", error: SyntaxError('unterminated quoted string at or near "\'and s.pe_calc > 0 and s.pe_calc < 40\n  and not s.cash_to_debt is null\n  and not s.operating_roa is null\n  and not s.op_cash_to_rev is null\n  and not s.net_income_to_rev is null\n  and not s.op_income_to_rev is null\n  and s.market_cap / 1e9 > 10)\n  select\n    *\n  from best_statement as b\n  where b.rk=1\n  order by b.market_cap_B desc"\nLINE 18:   \'and s.pe_calc > 0 and s.pe_calc < 40\n           ^\n')
2020-10-05 11:51:52,816 (2006954/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: unterminated quoted string at or near "\'and s.pe_calc > 0 and s.pe_calc < 40\n  and not s.cash_to_debt is null\n  and not s.operating_roa is null\n  and not s.op_cash_to_rev is null\n  and not s.net_income_to_rev is null\n  and not s.op_income_to_rev is null\n  and s.market_cap / 1e9 > 10)\n  select\n    *\n  from best_statement as b\n  where b.rk=1\n  order by b.market_cap_B desc"\nLINE 18:   \'and s.pe_calc > 0 and s.pe_calc < 40\n           ^\n\n'
2020-10-05 11:51:52,817 (2006954/MainThread) pgcli.pgexecute ERROR - sql: '\\i views.plsql', error: SyntaxError('unterminated quoted string at or near "\'and s.pe_calc > 0 and s.pe_calc < 40\n  and not s.cash_to_debt is null\n  and not s.operating_roa is null\n  and not s.op_cash_to_rev is null\n  and not s.net_income_to_rev is null\n  and not s.op_income_to_rev is null\n  and s.market_cap / 1e9 > 10)\n  select\n    *\n  from best_statement as b\n  where b.rk=1\n  order by b.market_cap_B desc"\nLINE 18:   \'and s.pe_calc > 0 and s.pe_calc < 40\n           ^\n')
2020-10-05 11:51:52,817 (2006954/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 398, in run\n    for result in pgspecial.execute(cur, sql):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: unterminated quoted string at or near "\'and s.pe_calc > 0 and s.pe_calc < 40\n  and not s.cash_to_debt is null\n  and not s.operating_roa is null\n  and not s.op_cash_to_rev is null\n  and not s.net_income_to_rev is null\n  and not s.op_income_to_rev is null\n  and s.market_cap / 1e9 > 10)\n  select\n    *\n  from best_statement as b\n  where b.rk=1\n  order by b.market_cap_B desc"\nLINE 18:   \'and s.pe_calc > 0 and s.pe_calc < 40\n           ^\n\n'
2020-12-13 16:41:18,627 (432665/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-12-13 16:44:23,966 (434118/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-12-15 22:21:46,471 (1921559/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-12-15 22:22:35,639 (1921965/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-12-15 22:24:30,360 (1921965/MainThread) pgcli.pgexecute ERROR - sql: 'create or replace view v_best_statements as\n  with best_statement as (\n  select\n  \ts.instrument_id,\n    s.name,\n\ts.symbol,\n\ts.year,\n\ts.market_cap / 1e9 as market_cap_B,\n\ts.pe_calc,\n\ts.div_yield,\n\ts.op_income_to_rev,\n\ts.net_income_to_rev,\n\ts.op_cash_to_rev,\n\ts.operating_roa,\n\ts.cash_to_debt,\n\trow_number() over (partition by s.symbol order by s.year desc) as rk\n  from v_statements as s\n  where s.year >= 2019\n  --and s.pe_calc > 0 and s.pe_calc < 40\n  and not s.cash_to_debt is null\n  and not s.operating_roa is null\n  and not s.op_cash_to_rev is null\n  and not s.net_income_to_rev is null\n  and not s.op_income_to_rev is null\n  and s.market_cap / 1e9 > 10)\n  select\n    *\n  from best_statement as b\n  where b.rk=1\n  order by b.market_cap_B desc', error: InvalidTableDefinition('cannot change name of view column "name" to "instrument_id"\n')
2020-12-15 22:24:30,361 (1921965/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.InvalidTableDefinition: cannot change name of view column "name" to "instrument_id"\n\n'
2020-12-15 22:24:30,361 (1921965/MainThread) pgcli.pgexecute ERROR - sql: '\\i views.plsql', error: InvalidTableDefinition('cannot change name of view column "name" to "instrument_id"\n')
2020-12-15 22:24:30,362 (1921965/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 398, in run\n    for result in pgspecial.execute(cur, sql):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.InvalidTableDefinition: cannot change name of view column "name" to "instrument_id"\n\n'
2020-12-16 00:51:08,583 (1992115/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-12-17 21:24:09,211 (3235273/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-12-17 21:35:58,604 (3235273/MainThread) pgcli.main ERROR - sql: '\\i /home/bk/src/fin/sql/sql02/tables.plsql;', error: FileNotFoundError(2, 'No such file or directory')
2020-12-17 21:35:58,605 (3235273/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/main.py", line 634, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/usr/lib/python3.8/site-packages/pgcli/main.py", line 880, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 398, in run\n    for result in pgspecial.execute(cur, sql):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 398, in run\n    for result in pgspecial.execute(cur, sql):\n  File "/usr/lib/python3.8/site-packages/pgspecial/main.py", line 90, in execute\n    return special_cmd.handler(cur=cur, pattern=pattern, verbose=verbose)\n  File "/usr/lib/python3.8/site-packages/pgspecial/iocommands.py", line 149, in copy\n    file = io.open(expanduser(file_name.strip("\'")), mode=open_mode, encoding=\'utf-8\')\nFileNotFoundError: [Errno 2] No such file or directory: \'data/sectors.csv\'\n'
2020-12-17 21:42:20,928 (3243854/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-12-17 21:43:25,197 (3243854/MainThread) pgcli.pgexecute ERROR - sql: 'select * from v_best_statements as b\nleft join instrument_gdratings g on b.g.instrument_id = b.instrument_id', error: UndefinedTable('invalid reference to FROM-clause entry for table "g"\nLINE 2: left join instrument_gdratings g on b.g.instrument_id = b.in...\n                                            ^\nHINT:  There is an entry for table "g", but it cannot be referenced from this part of the query.\n')
2020-12-17 21:43:25,198 (3243854/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedTable: invalid reference to FROM-clause entry for table "g"\nLINE 2: left join instrument_gdratings g on b.g.instrument_id = b.in...\n                                            ^\nHINT:  There is an entry for table "g", but it cannot be referenced from this part of the query.\n\n'
2020-12-17 21:43:59,208 (3243854/MainThread) pgcli.pgexecute ERROR - sql: 'select * from v_best_statements, g.gd_rating as b\nleft join instrument_gdratings as g on b.g.instrument_id = b.instrument_id', error: UndefinedTable('relation "g.gd_rating" does not exist\nLINE 1: select * from v_best_statements, g.gd_rating as b\n                                         ^\n')
2020-12-17 21:43:59,208 (3243854/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedTable: relation "g.gd_rating" does not exist\nLINE 1: select * from v_best_statements, g.gd_rating as b\n                                         ^\n\n'
2020-12-17 21:44:25,231 (3243854/MainThread) pgcli.pgexecute ERROR - sql: 'select * from v_best_statements, g.gd_rating as b\nleft join instrument_gdratings as g on g.instrument_id = b.instrument_id', error: UndefinedTable('relation "g.gd_rating" does not exist\nLINE 1: select * from v_best_statements, g.gd_rating as b\n                                         ^\n')
2020-12-17 21:44:25,231 (3243854/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedTable: relation "g.gd_rating" does not exist\nLINE 1: select * from v_best_statements, g.gd_rating as b\n                                         ^\n\n'
2020-12-17 21:49:34,986 (3243854/MainThread) pgcli.pgexecute ERROR - sql: 'drop view v_statements', error: DependentObjectsStillExist('cannot drop view v_statements because other objects depend on it\nDETAIL:  view v_best_statements depends on view v_statements\nHINT:  Use DROP ... CASCADE to drop the dependent objects too.\n')
2020-12-17 21:49:34,986 (3243854/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.DependentObjectsStillExist: cannot drop view v_statements because other objects depend on it\nDETAIL:  view v_best_statements depends on view v_statements\nHINT:  Use DROP ... CASCADE to drop the dependent objects too.\n\n'
2020-12-17 21:51:27,773 (3248042/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-12-17 22:07:28,877 (3255441/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-12-17 22:07:34,361 (3255441/MainThread) pgcli.pgexecute ERROR - sql: 'create or replace view v_best_statements as\n  with best_statement as (\n  select\n  \ts.instrument_id,\n    s.name,\n\ts.symbol,\n\ts.gd_rating,\n\ts.market_cap / 1e9 as market_cap_B,\n\ts.pe_calc,\n\ts.div_yield,\n\ts.op_income_to_rev,\n\ts.net_income_to_rev,\n\ts.op_cash_to_rev,\n\ts.operating_roa,\n\ts.cash_to_debt,\n\trow_number() over (partition by s.symbol order by s.year desc) as rk\n  from v_statements as s\n  where s.year >= 2019\n  --and s.pe_calc > 0 and s.pe_calc < 40\n  and not s.cash_to_debt is null\n  and not s.operating_roa is null\n  and not s.op_cash_to_rev is null\n  and not s.net_income_to_rev is null\n  and not s.op_income_to_rev is null\n  and s.market_cap / 1e9 > 0\n  and s.pe_calc > 0\n  and s.gd_rating >= 4\n  and s.operating_roa >= 0.1\n  and s.op_income_to_rev >= 0.15\n  and s.op_income_to_rev > s.net_income_to_rev\n  and s.op_cash_to_rev > s.op_income_to_rev\n  and s.cash_to_debt > 0.10)\n  select\n    *\n  from best_statement as b\n  where b.rk=1\n  order by b.market_cap_B desc', error: InvalidTableDefinition('cannot drop columns from view\n')
2020-12-17 22:07:34,361 (3255441/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.InvalidTableDefinition: cannot drop columns from view\n\n'
2020-12-17 22:07:34,362 (3255441/MainThread) pgcli.pgexecute ERROR - sql: '\\i views.plsql', error: InvalidTableDefinition('cannot drop columns from view\n')
2020-12-17 22:07:34,362 (3255441/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 398, in run\n    for result in pgspecial.execute(cur, sql):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.InvalidTableDefinition: cannot drop columns from view\n\n'
2020-12-17 22:43:52,353 (3255441/MainThread) pgcli.pgexecute ERROR - sql: 'create or replace view v_best_revenue_history as\n  select \n    s.instrument_id,\n\ts.name,\n\ts.symbol,\n\ts.year,\n\ts.revenue\n  from v_statments as s\n  inner join v_best_statements as b\n  on b.instrument_id = s.instrument_id\n  order by \n    s.name, \n\ts.year', error: UndefinedTable('relation "v_statments" does not exist\nLINE 8:   from v_statments as s\n               ^\n')
2020-12-17 22:43:52,353 (3255441/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedTable: relation "v_statments" does not exist\nLINE 8:   from v_statments as s\n               ^\n\n'
2020-12-17 22:43:52,355 (3255441/MainThread) pgcli.pgexecute ERROR - sql: '\\i views.plsql', error: UndefinedTable('relation "v_statments" does not exist\nLINE 8:   from v_statments as s\n               ^\n')
2020-12-17 22:43:52,356 (3255441/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 398, in run\n    for result in pgspecial.execute(cur, sql):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedTable: relation "v_statments" does not exist\nLINE 8:   from v_statments as s\n               ^\n\n'
2020-12-17 22:54:11,099 (3277026/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-12-17 22:58:17,886 (3277026/MainThread) pgcli.pgexecute ERROR - sql: 's', error: SyntaxError('syntax error at or near "s"\nLINE 1: s\n        ^\n')
2020-12-17 22:58:17,887 (3277026/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "s"\nLINE 1: s\n        ^\n\n'
